
services:

  backend:
    image: node
    build:
      context: ./Backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - database_volume:/Database
    env_file:
      - .env
    networks:
      - transcendence

  server:
    image: nginx
    build:
      context: ./Server
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    networks:
      - transcendence
    depends_on:
      - backend

networks:
  transcendence:
    name: transcendence
    driver: bridge

volumes:
  database_volume:
    driver: local
    driver_opts:
      type: none
      device: ./Database
      o: bind