
services:

  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    restart: always
    environment:
      - DB_PATH=/data/pong.db
    volumes:
      # - database_volume:/usr/app/pong.db
      - dbdata:/data
    env_file:
      - .env
    networks:
      - transcendence
    ports:
      - "3000:3000"

  server:
    build:
      context: .
      dockerfile: Server/Dockerfile
    restart: always
    env_file:
      - .env
    networks:
      - transcendence
    depends_on:
      - backend
    ports:
      - "8443:443"

networks:
  transcendence:
    name: transcendence
    driver: bridge

volumes:
  dbdata:
  # database_volume:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: ./Database
  #     o: bind