
services:

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - database_volume:/Database
      - ngrok_shared:/shared/ngrok
    env_file:
      - .env
    networks:
      - transcendence
    ports:
      - "3000:3000"

  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    restart: always
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    env_file:
      - .env
    networks:
      - transcendence
    depends_on:
      - backend
    volumes:
      - ngrok_shared:/shared/ngrok
    ports:
      - "8443:443"
      - "4040:4040"

networks:
  transcendence:
    name: transcendence
    driver: bridge

volumes:
  database_volume:
  ngrok_shared:
    # driver: local
    # driver_opts:
    #   type: none
    #   device: ./Database
    #   o: bind