
services:

  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    restart: always
    environment:
      - DB_PATH=/data/pong.db
    volumes:
      # - database_volume:/usr/app/pong.db
      - dbdata:/data
    init: true
    stop_signal: SIGTERM
    stop_grace_period: 3s
    env_file:
      - .env
    networks:
      - transcendence
    ports:
      - "3000:3000"

  server:
    build:
      context: .
      dockerfile: Server/Dockerfile
    restart: always
    stop_grace_period: 1s
    env_file:
      - .env
    networks:
      - transcendence
    depends_on:
      - backend
    ports:
      - "8443:443"

networks:
  transcendence:
    name: transcendence
    driver: bridge

volumes:
  dbdata: