
# # execute tests on push to main branch
# on:
#  push:
#    branches: [main] 
#   workflow_dispatch: 
# # jobs run on ubuntu-latest
# jobs:
#   test:
#     runs-on: ubuntu-latest

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       # Gives workflow access to the repository
#       - name: Checkout code
#         uses: actions/checkout@v3

#       # Node.js for runner to run Playwright tests
#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '20'

#       # Install dependencies for runner
#       - name: Install dependencies
#         run: npm ci

#       # Makes it possible to run program in a Docker container
#       - name: Setup Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       # execute makefile to build docker containers
#       - name: Build project
#         run: make

#       # how do we know when the services are ready?
#       - name: Wait for services to be ready
#         run: |
#         run: |
#           echo "Waiting for backend to be ready..."
#           for i in {1..30}; do
#             if curl -s http://localhost:8443; then
#               echo "Backend is up!"
#               break
#             fi
#             echo "Not ready yet, waiting 10s..."
#             sleep 10
#           done

#       # start tests
#       - name: Run Playwright tests
#         run: npx playwright test --reporter=github

#       # stop docker services
#       - name: Stop services
#         run: make prune
